import type { Activity, AnalyticsPoint, Stat } from "@/src/types";

export const dashboardStats: Stat[] = [
  { label: "Active Projects", value: "12", change: "+8% this month", tone: "primary" },
  { label: "Completion Rate", value: "84%", change: "+6% vs last cycle", tone: "success" },
  { label: "Delayed Tasks", value: "6", change: "-3 from last week", tone: "warning" },
  { label: "Team Productivity", value: "91", change: "+4 points", tone: "info" },
];

export const activity: Activity[] = [
  // --- Project: Design System v2 (p-design-system) ---
  // To showcase >10 activities: 12 activities, sorted newest first
  {
    id: "ds-12",
    actorId: "u-manager-3",
    action: "assigned",
    subject: "Accessible focus indicators to Kabir Verma",
    timestamp: "2026-06-22T11:00:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-11",
    actorId: "u-employee-6",
    action: "completed task",
    subject: "Build glassmorphism card variants",
    timestamp: "2026-06-20T09:42:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-10",
    actorId: "u-employee-6",
    action: "commented on",
    subject: "Build glassmorphism card variants",
    timestamp: "2026-06-16T16:45:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-9",
    actorId: "u-employee-2",
    action: "commented on",
    subject: "Create color token documentation",
    timestamp: "2026-06-15T14:22:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-8",
    actorId: "u-employee-6",
    action: "started task",
    subject: "Build glassmorphism card variants",
    timestamp: "2026-06-14T09:15:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-7",
    actorId: "u-employee-2",
    action: "started task",
    subject: "Create color token documentation",
    timestamp: "2026-06-13T10:30:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-6",
    actorId: "u-manager-3",
    action: "assigned",
    subject: "Build glassmorphism card variants to Meera Iyer",
    timestamp: "2026-06-12T09:05:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-5",
    actorId: "u-manager-3",
    action: "assigned",
    subject: "Create color token documentation to Sara Khan",
    timestamp: "2026-06-12T09:00:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-4",
    actorId: "u-manager-3",
    action: "created task",
    subject: "Accessible focus indicators",
    timestamp: "2026-06-11T11:10:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-3",
    actorId: "u-manager-3",
    action: "created task",
    subject: "Build glassmorphism card variants",
    timestamp: "2026-06-11T11:05:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-2",
    actorId: "u-manager-3",
    action: "created task",
    subject: "Create color token documentation",
    timestamp: "2026-06-11T11:00:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "ds-1",
    actorId: "u-manager-3",
    action: "created project",
    subject: "Design System v2",
    timestamp: "2026-06-10T10:00:00.000Z",
    projectId: "p-design-system",
  },

  // --- General / Workspace Activities ---
  {
    id: "a-1",
    actorId: "u-manager-1",
    action: "moved",
    subject: "Project filters to review",
    timestamp: "2026-06-22T08:30:00.000Z",
    projectId: "p-command-center",
  },
  {
    id: "a-2",
    actorId: "u-employee-2",
    action: "attached research to",
    subject: "Onboarding checklist",
    timestamp: "2026-06-21T16:15:00.000Z",
    projectId: "p-onboarding",
  },
  {
    id: "a-3",
    actorId: "u-admin-1",
    action: "approved",
    subject: "Quarterly reporting hub",
    timestamp: "2026-06-20T11:05:00.000Z",
    projectId: "p-reporting",
  },
  {
    id: "a-4",
    actorId: "u-employee-6",
    action: "completed",
    subject: "Glassmorphism card variants",
    timestamp: "2026-06-20T09:42:00.000Z",
    projectId: "p-design-system",
  },
  {
    id: "a-5",
    actorId: "u-manager-3",
    action: "created project",
    subject: "Dashboard Redesign",
    timestamp: "2026-06-19T14:30:00.000Z",
    projectId: "p-dashboard-v2",
  },
  {
    id: "a-6",
    actorId: "u-employee-4",
    action: "started",
    subject: "Rate limiter implementation",
    timestamp: "2026-06-19T10:15:00.000Z",
    projectId: "p-api-gateway",
  },
  {
    id: "a-7",
    actorId: "u-manager-4",
    action: "assigned",
    subject: "CI pipeline integration to backlog",
    timestamp: "2026-06-18T16:00:00.000Z",
    projectId: "p-test-automation",
  },
  {
    id: "a-8",
    actorId: "u-employee-7",
    action: "deployed",
    subject: "Alert notification system",
    timestamp: "2026-06-18T11:30:00.000Z",
    projectId: "p-monitoring",
  },
];

export const analytics: AnalyticsPoint[] = [
  { label: "Jan", completed: 42, delayed: 8, productivity: 74 },
  { label: "Feb", completed: 51, delayed: 7, productivity: 79 },
  { label: "Mar", completed: 48, delayed: 9, productivity: 76 },
  { label: "Apr", completed: 63, delayed: 6, productivity: 84 },
  { label: "May", completed: 68, delayed: 5, productivity: 88 },
  { label: "Jun", completed: 72, delayed: 4, productivity: 91 },
  { label: "Jul", completed: 58, delayed: 7, productivity: 82 },
  { label: "Aug", completed: 65, delayed: 5, productivity: 86 },
  { label: "Sep", completed: 71, delayed: 3, productivity: 90 },
  { label: "Oct", completed: 76, delayed: 4, productivity: 92 },
  { label: "Nov", completed: 69, delayed: 6, productivity: 87 },
  { label: "Dec", completed: 80, delayed: 3, productivity: 94 },
];
