import type { Project } from "@/src/types";

export const projects: Project[] = [
  {
    id: "p-command-center",
    name: "Executive Command Center",
    description: "Admin dashboard with company health KPIs, project tracking, and resource allocation views.",
    ownerId: "u-manager-1",
    teamId: "t-platform",
    status: "active",
    progress: 72,
    startDate: "2026-04-15",
    dueDate: "2026-07-12",
    budget: 128000,
    delayedTasks: 2,
  },
  {
    id: "p-permissions",
    name: "Role Permission Matrix",
    description: "Implement admin, manager, and employee access control across all modules.",
    ownerId: "u-manager-1",
    teamId: "t-platform",
    status: "planning",
    progress: 24,
    startDate: "2026-06-01",
    dueDate: "2026-08-05",
    budget: 84000,
    delayedTasks: 0,
  },
  {
    id: "p-onboarding",
    name: "Team Onboarding Flow",
    description: "First-week employee onboarding journey with checklists, mentorship matching, and progress tracking.",
    ownerId: "u-manager-2",
    teamId: "t-growth",
    status: "at-risk",
    progress: 58,
    startDate: "2026-03-20",
    dueDate: "2026-07-01",
    budget: 96000,
    delayedTasks: 4,
  },
  {
    id: "p-reporting",
    name: "Quarterly Reporting Hub",
    description: "Executive analytics with completion rates, team productivity, and resource allocation insights.",
    ownerId: "u-admin-1",
    teamId: "t-ops",
    status: "completed",
    progress: 100,
    startDate: "2026-01-10",
    dueDate: "2026-06-18",
    budget: 64000,
    delayedTasks: 0,
  },
  {
    id: "p-design-system",
    name: "Design System v2",
    description: "Unified component library with glassmorphism tokens, accessibility patterns, and documentation.",
    ownerId: "u-manager-3",
    teamId: "t-design",
    status: "active",
    progress: 65,
    startDate: "2026-05-01",
    dueDate: "2026-08-20",
    budget: 112000,
    delayedTasks: 1,
  },
  {
    id: "p-api-gateway",
    name: "API Gateway Migration",
    description: "Migrate REST endpoints to a unified gateway with rate limiting, caching, and observability.",
    ownerId: "u-manager-1",
    teamId: "t-platform",
    status: "active",
    progress: 41,
    startDate: "2026-05-15",
    dueDate: "2026-09-30",
    budget: 156000,
    delayedTasks: 3,
  },
  {
    id: "p-referral",
    name: "Referral Program",
    description: "Internal referral tracking with incentive management and conversion analytics.",
    ownerId: "u-manager-2",
    teamId: "t-growth",
    status: "planning",
    progress: 12,
    startDate: "2026-06-10",
    dueDate: "2026-10-15",
    budget: 72000,
    delayedTasks: 0,
  },
  {
    id: "p-test-automation",
    name: "Test Automation Suite",
    description: "End-to-end and integration test coverage with CI/CD pipeline integration.",
    ownerId: "u-manager-4",
    teamId: "t-qa",
    status: "active",
    progress: 53,
    startDate: "2026-04-01",
    dueDate: "2026-08-15",
    budget: 88000,
    delayedTasks: 2,
  },
  {
    id: "p-dashboard-v2",
    name: "Dashboard Redesign",
    description: "Role-specific dashboard layouts with interactive widgets and real-time data feeds.",
    ownerId: "u-manager-3",
    teamId: "t-design",
    status: "planning",
    progress: 18,
    startDate: "2026-06-15",
    dueDate: "2026-09-01",
    budget: 104000,
    delayedTasks: 0,
  },
  {
    id: "p-monitoring",
    name: "Infrastructure Monitoring",
    description: "Real-time alerting, uptime tracking, and incident management dashboard.",
    ownerId: "u-admin-2",
    teamId: "t-ops",
    status: "active",
    progress: 78,
    startDate: "2026-02-01",
    dueDate: "2026-07-20",
    budget: 92000,
    delayedTasks: 1,
  },
];
