import type { Task } from "@/src/types";

export const tasks: Task[] = [
  // ── Command Center ─────────────────────────────────────
  {
    id: "task-1",
    title: "Map admin dashboard KPIs",
    description: "Define company-level signals for project health and resource allocation.",
    projectId: "p-command-center",
    assigneeId: "u-admin-1",
    status: "completed",
    priority: "high",
    deadline: "2026-06-20",
    comments: 8,
    attachments: 2,
    createdAt: "2026-04-15",
  },
  {
    id: "task-2",
    title: "Build project table filters",
    description: "Add search, status filters, and sortable columns for active projects.",
    projectId: "p-command-center",
    assigneeId: "u-employee-1",
    status: "in-progress",
    priority: "urgent",
    deadline: "2026-06-28",
    comments: 5,
    attachments: 1,
    createdAt: "2026-05-02",
  },
  {
    id: "task-3",
    title: "Implement stats card animations",
    description: "Add count-up animations and skeleton loading states to KPI stat cards.",
    projectId: "p-command-center",
    assigneeId: "u-employee-6",
    status: "review",
    priority: "medium",
    deadline: "2026-06-25",
    comments: 3,
    attachments: 0,
    createdAt: "2026-05-10",
  },

  // ── Permissions ─────────────────────────────────────────
  {
    id: "task-4",
    title: "Review permission inheritance",
    description: "Validate admin, manager, and employee access rules against product policy.",
    projectId: "p-permissions",
    assigneeId: "u-manager-1",
    status: "review",
    priority: "medium",
    deadline: "2026-07-04",
    comments: 3,
    attachments: 0,
    createdAt: "2026-06-01",
  },
  {
    id: "task-5",
    title: "Build role-based nav guard",
    description: "Implement client-side route protection based on user role permissions.",
    projectId: "p-permissions",
    assigneeId: "u-employee-4",
    status: "todo",
    priority: "high",
    deadline: "2026-07-10",
    comments: 2,
    attachments: 1,
    createdAt: "2026-06-05",
  },

  // ── Onboarding ──────────────────────────────────────────
  {
    id: "task-6",
    title: "Create onboarding checklist",
    description: "Draft first-week team onboarding milestones for new employees.",
    projectId: "p-onboarding",
    assigneeId: "u-employee-5",
    status: "todo",
    priority: "high",
    deadline: "2026-06-30",
    comments: 6,
    attachments: 3,
    createdAt: "2026-03-25",
  },
  {
    id: "task-7",
    title: "Design mentor matching UI",
    description: "Create interface for pairing new hires with team mentors.",
    projectId: "p-onboarding",
    assigneeId: "u-employee-2",
    status: "in-progress",
    priority: "medium",
    deadline: "2026-06-29",
    comments: 4,
    attachments: 2,
    createdAt: "2026-04-10",
  },
  {
    id: "task-8",
    title: "Implement progress tracker",
    description: "Build onboarding progress visualization with milestone completion states.",
    projectId: "p-onboarding",
    assigneeId: "u-employee-8",
    status: "backlog",
    priority: "low",
    deadline: "2026-07-08",
    comments: 1,
    attachments: 0,
    createdAt: "2026-04-15",
  },

  // ── Reporting ───────────────────────────────────────────
  {
    id: "task-9",
    title: "Audit reporting layout",
    description: "Check analytics screens for executive readability and responsive behavior.",
    projectId: "p-reporting",
    assigneeId: "u-employee-3",
    status: "completed",
    priority: "low",
    deadline: "2026-06-15",
    comments: 2,
    attachments: 1,
    createdAt: "2026-01-15",
  },
  {
    id: "task-10",
    title: "Export PDF reports",
    description: "Generate downloadable PDF summaries of quarterly analytics data.",
    projectId: "p-reporting",
    assigneeId: "u-employee-7",
    status: "completed",
    priority: "medium",
    deadline: "2026-06-12",
    comments: 5,
    attachments: 2,
    createdAt: "2026-02-01",
  },

  // ── Design System ───────────────────────────────────────
  {
    id: "task-11",
    title: "Create color token documentation",
    description: "Document all color-mix based tokens with usage examples and contrast ratios.",
    projectId: "p-design-system",
    assigneeId: "u-employee-2",
    status: "in-progress",
    priority: "high",
    deadline: "2026-07-05",
    comments: 7,
    attachments: 4,
    createdAt: "2026-05-05",
  },
  {
    id: "task-12",
    title: "Build glassmorphism card variants",
    description: "Implement card surfaces with gradient backgrounds, accent borders, and blur effects.",
    projectId: "p-design-system",
    assigneeId: "u-employee-6",
    status: "completed",
    priority: "urgent",
    deadline: "2026-06-20",
    comments: 9,
    attachments: 3,
    createdAt: "2026-05-10",
  },
  {
    id: "task-13",
    title: "Accessible focus indicators",
    description: "Add visible focus rings to all interactive components meeting WCAG 2.1 AA.",
    projectId: "p-design-system",
    assigneeId: "u-manager-3",
    status: "todo",
    priority: "high",
    deadline: "2026-07-15",
    comments: 2,
    attachments: 0,
    createdAt: "2026-06-01",
  },

  // ── API Gateway ─────────────────────────────────────────
  {
    id: "task-14",
    title: "Rate limiter implementation",
    description: "Add token bucket rate limiting per API key with configurable thresholds.",
    projectId: "p-api-gateway",
    assigneeId: "u-employee-4",
    status: "in-progress",
    priority: "urgent",
    deadline: "2026-07-01",
    comments: 6,
    attachments: 1,
    createdAt: "2026-05-20",
  },
  {
    id: "task-15",
    title: "Response caching layer",
    description: "Implement Redis-backed response caching with TTL and invalidation strategies.",
    projectId: "p-api-gateway",
    assigneeId: "u-employee-1",
    status: "backlog",
    priority: "medium",
    deadline: "2026-08-01",
    comments: 3,
    attachments: 0,
    createdAt: "2026-05-25",
  },
  {
    id: "task-16",
    title: "API health check endpoint",
    description: "Create standardized health check returning service status and dependencies.",
    projectId: "p-api-gateway",
    assigneeId: "u-employee-7",
    status: "todo",
    priority: "medium",
    deadline: "2026-07-15",
    comments: 1,
    attachments: 0,
    createdAt: "2026-06-01",
  },

  // ── Test Automation ─────────────────────────────────────
  {
    id: "task-17",
    title: "E2E test for auth flow",
    description: "Write end-to-end tests covering login, registration, and role switching.",
    projectId: "p-test-automation",
    assigneeId: "u-employee-3",
    status: "in-progress",
    priority: "high",
    deadline: "2026-07-10",
    comments: 4,
    attachments: 1,
    createdAt: "2026-04-10",
  },
  {
    id: "task-18",
    title: "CI pipeline integration",
    description: "Configure test suite to run on every PR with parallel execution and reporting.",
    projectId: "p-test-automation",
    assigneeId: "u-manager-4",
    status: "backlog",
    priority: "medium",
    deadline: "2026-07-20",
    comments: 2,
    attachments: 0,
    createdAt: "2026-04-15",
  },

  // ── Referral ────────────────────────────────────────────
  {
    id: "task-19",
    title: "Referral tracking schema",
    description: "Design database schema for referral sources, conversions, and reward tiers.",
    projectId: "p-referral",
    assigneeId: "u-employee-5",
    status: "backlog",
    priority: "low",
    deadline: "2026-08-01",
    comments: 1,
    attachments: 0,
    createdAt: "2026-06-12",
  },

  // ── Dashboard Redesign ──────────────────────────────────
  {
    id: "task-20",
    title: "Role-specific widget layouts",
    description: "Design admin, manager, and employee dashboard widget arrangements.",
    projectId: "p-dashboard-v2",
    assigneeId: "u-employee-2",
    status: "todo",
    priority: "high",
    deadline: "2026-07-15",
    comments: 5,
    attachments: 2,
    createdAt: "2026-06-15",
  },
  {
    id: "task-21",
    title: "Interactive chart widgets",
    description: "Build real-time updating charts with drill-down and export capabilities.",
    projectId: "p-dashboard-v2",
    assigneeId: "u-employee-6",
    status: "backlog",
    priority: "medium",
    deadline: "2026-08-01",
    comments: 2,
    attachments: 1,
    createdAt: "2026-06-18",
  },

  // ── Monitoring ──────────────────────────────────────────
  {
    id: "task-22",
    title: "Uptime monitoring dashboard",
    description: "Build real-time service status page with historical uptime graphs.",
    projectId: "p-monitoring",
    assigneeId: "u-employee-7",
    status: "review",
    priority: "high",
    deadline: "2026-07-01",
    comments: 6,
    attachments: 2,
    createdAt: "2026-02-10",
  },
  {
    id: "task-23",
    title: "Alert notification system",
    description: "Configure Slack and email alerts for downtime events and threshold breaches.",
    projectId: "p-monitoring",
    assigneeId: "u-employee-7",
    status: "completed",
    priority: "urgent",
    deadline: "2026-06-15",
    comments: 8,
    attachments: 3,
    createdAt: "2026-02-15",
  },
];
