import type { Team } from "@/src/types";

export const teams: Team[] = [
  {
    id: "t-platform",
    name: "Platform",
    description: "Core infrastructure, APIs, and developer tooling",
    leadId: "u-manager-1",
    memberIds: ["u-manager-1", "GTF-1005", "GTF-1200"],
    projectIds: ["p-command-center", "p-permissions", "p-api-gateway"],
    health: 92,
    workingDaysPerWeek: 5,
    velocity: 38,
    type: "Engineering",
  },
  {
    id: "t-growth",
    name: "Growth",
    description: "User acquisition, onboarding, and engagement",
    leadId: "u-manager-2",
    memberIds: ["u-manager-2"],
    projectIds: ["p-onboarding", "p-referral"],
    health: 86,
    workingDaysPerWeek: 5,
    velocity: 31,
    type: "Marketing",
  },
  {
    id: "t-design",
    name: "Design",
    description: "Product design, design systems, and brand identity",
    leadId: "u-manager-3",
    memberIds: ["u-manager-3", "GTF-1340"],
    projectIds: ["p-design-system", "p-dashboard-v2"],
    health: 94,
    workingDaysPerWeek: 5,
    velocity: 28,
    type: "Design",
  },
  {
    id: "t-qa",
    name: "QA Testing",
    description: "Test automation, regression, and release validation",
    leadId: "u-manager-4",
    memberIds: ["u-manager-4"],
    projectIds: ["p-test-automation"],
    health: 79,
    workingDaysPerWeek: 5,
    velocity: 24,
    type: "QA",
  },
  {
    id: "t-ops",
    name: "Operations",
    description: "Business operations, support desk, and compliance monitoring",
    leadId: "u-manager-1",
    memberIds: ["u-manager-1", "GTF-2210", "GTF-1844", "GTF-1980", "GTF-1042"],
    projectIds: ["p-reporting", "p-monitoring"],
    health: 88,
    workingDaysPerWeek: 5,
    velocity: 32,
    type: "Operations",
  },
];
