import type { User } from "@/src/types";

export const users: User[] = [
  // ── Admins ──────────────────────────────────────────────
  {
    id: "u-admin-1",
    name: "Maya Rao",
    role: "admin",
    title: "VP Operations",
    email: "maya.rao@workos.test",
    teamId: "t-ops",
    avatar: "MR",
    utilization: 78,
    performance: 94,
    department: "Operations",
  },
  {
    id: "u-admin-2",
    name: "Vikram Joshi",
    role: "admin",
    title: "CTO",
    email: "vikram.joshi@workos.test",
    teamId: "t-platform",
    avatar: "VJ",
    utilization: 65,
    performance: 97,
    department: "Technology",
  },

  // ── Managers ────────────────────────────────────────────
  {
    id: "u-manager-1",
    name: "Sourabh Yadav",
    role: "manager",
    title: "Engineering Manager",
    email: "sourabh.yadav@gtftechnologies.com",
    teamId: "t-ops",
    avatar: "SY",
    utilization: 86,
    performance: 91,
    department: "Operations",
    canCreateTeam: true,
  },
  {
    id: "u-manager-2",
    name: "Nora Shah",
    role: "manager",
    title: "Product Lead",
    email: "nora.shah@workos.test",
    teamId: "t-growth",
    avatar: "NS",
    utilization: 81,
    performance: 89,
    department: "Marketing",
    canCreateTeam: true,
  },
  {
    id: "u-manager-3",
    name: "Kabir Verma",
    role: "manager",
    title: "Design Lead",
    email: "kabir.verma@workos.test",
    teamId: "t-design",
    avatar: "KV",
    utilization: 74,
    performance: 92,
    department: "Design",
    canCreateTeam: true,
  },
  {
    id: "u-manager-4",
    name: "Priya Nair",
    role: "manager",
    title: "QA Lead",
    email: "priya.nair@workos.test",
    teamId: "t-qa",
    avatar: "PN",
    utilization: 79,
    performance: 88,
    department: "QA",
    canCreateTeam: true,
  },

  // ── Employees (from User Screenshot 1) ──────────────────
  {
    id: "GTF-2210",
    name: "Neha Kapoor",
    role: "employee",
    title: "Operations Associate",
    email: "neha.kapoor@gtftechnologies.com",
    teamId: "t-ops",
    avatar: "NK",
    utilization: 75,
    performance: 94,
    department: "Operations",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1844",
    name: "Rohan Iyer",
    role: "employee",
    title: "Support Specialist",
    email: "rohan.iyer@gtftechnologies.com",
    teamId: "t-ops",
    avatar: "RI",
    utilization: 70,
    performance: 88,
    department: "Support",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1980",
    name: "Fatima Khan",
    role: "employee",
    title: "Operations Lead",
    email: "fatima.khan@gtftechnologies.com",
    teamId: "t-ops",
    avatar: "FK",
    utilization: 80,
    performance: 90,
    department: "Operations",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1042",
    name: "Kuldeep",
    role: "employee",
    title: "Operations Associate",
    email: "kuldeep.choudhary@gtftechnologies.com",
    teamId: "t-ops",
    avatar: "K",
    utilization: 85,
    performance: 82,
    department: "Operations",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1005",
    name: "Kuldeep Choudhary",
    role: "employee",
    title: "Software Engineer",
    email: "kuldeep.c@gtftechnologies.com",
    teamId: "t-platform",
    avatar: "KC",
    utilization: 90,
    performance: 88,
    department: "Technology",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1200",
    name: "Amit Sharma",
    role: "employee",
    title: "Frontend Developer",
    email: "amit.sharma@gtftechnologies.com",
    teamId: "t-platform",
    avatar: "AS",
    utilization: 78,
    performance: 85,
    department: "Technology",
    createdBy: "u-manager-1",
    workingDaysPerWeek: 5,
  },
  {
    id: "GTF-1340",
    name: "Shweta Patel",
    role: "employee",
    title: "UI/UX Designer",
    email: "shweta.patel@gtftechnologies.com",
    teamId: "t-design",
    avatar: "SP",
    utilization: 72,
    performance: 91,
    department: "Tech/Design",
    createdBy: "u-manager-3",
    workingDaysPerWeek: 5,
  },
];
